### PR TITLE
WSO2 'Functions' feature added (FaaS implementation for WSO2 cloud)

### PR DESCRIPTION
**Pull request by pranavan15**
Complete back-end implementation for FaaS project added.

### CODE REVIEW

**Comment by chamilaadhi** [comment]
Hi Pranavan

When try to build it I get a dependency resolving issue. Seems like you haven't added the Nimbus JOSE JWT related repositories. Can you add the new repository urls and do a PR. (try building it on a clean repo to find any other missing dependencies as well)

Thanks
Chamila

**Comment by pranavan15** [comment]
Hi Chamila,

Sorry for the trouble :) 
WSO2 bundle version of jose-jwt dependency was missed out in the pom. Though, it worked for me earlier, since maven has cached the dependencies in my local machine.
I resolved this issue now. built and checked it on a clean repo as well.
Hope there won't be any more problem. Can you please check and let me know?

Thanks and Regards,
S.Pranavan

**Comment by chamilaadhi** [comment]
Thanks. Now it is getting build. will do some testing and merge it

**Comment by pranavan15** [comment]
Thanks Chamila.

**Pull request merged**
