### PR TITLE
Fix sending error response when no response body is sent

### PR DESCRIPTION
**Pull request by SachiniSiriwardene**
Fixes https://github.com/wso2/product-apim/issues/10792
https://github.com/wso2/product-apim/issues/10936

### CODE REVIEW

**Review by dushaniw — APPROVED** [review]

**Comment by tharindu1st** [comment]
git action https://github.com/SachiniSiriwardene/carbon-apimgt-1/actions/runs/724763230

**Comment by malinthaprasan** [comment]
```
    private static void processResponsePayload(ExtensionResponseDTO extensionResponseDTO,
                                               MessageContext messageContext) {

        org.apache.axis2.context.MessageContext axis2MC = ((Axis2MessageContext) messageContext).
                getAxis2MessageContext();
        String contentType = getAxis2TransportHeaders(axis2MC).get(APIConstants.HEADER_CONTENT_TYPE);
        if (extensionResponseDTO.getPayload() != null && contentType != null) {
            // if payload null, not modifying existing payload
            try {
                String payload = IOUtils.toString(extensionResponseDTO.getPayload());
                // based on Content-Type header reset the payload
                if (StringUtils.equals(contentType, APIConstants.APPLICATION_JSON_MEDIA_TYPE)) {
                    JsonUtil.removeJsonPayload(axis2MC);
                    JsonUtil.getNewJsonPayload(axis2MC, payload, true, true);
                    axis2MC.setProperty(Constants.Configuration.MESSAGE_TYPE, APIConstants.APPLICATION_JSON_MEDIA_TYPE);
                    axis2MC.setProperty(Constants.Configuration.CONTENT_TYPE, APIConstants.APPLICATION_JSON_MEDIA_TYPE);
                } else {
                    // by default treat payload in well formed xml format
                    OMElement omElement = AXIOMUtil.stringToOM(payload);
                    SOAPEnvelope env = TransportUtils.createSOAPEnvelope(omElement);
                    messageContext.setEnvelope(env);
                    axis2MC.setProperty(Constants.Configuration.MESSAGE_TYPE,
                            APIConstants.APPLICATION_XML_SOAP_MEDIA_TYPE);
                }
                axis2MC.removeProperty(APIConstants.NO_ENTITY_BODY);
            } catch (IOException | XMLStreamException e) {
                log.error("Error while setting payload " + axis2MC.getLogIDString(), e);
            }
        } else if (extensionResponseDTO.getPayload() == null) {
            try {
                RelayUtils.discardRequestMessage(((Axis2MessageContext) messageContext).getAxis2MessageContext());
            } catch (AxisFault axisFault) {
                // handle error
            }
        }
    }
```

**Comment by malinthaprasan** [comment]
Since APIM doesn't build payload, content length may not be always present. So better to discard the input stream.
Could you please check above in both APIM and OB

**Review by malinthaprasan — CHANGES_REQUESTED** [review]
Due to code changes

**Comment by tharikaGitHub** [comment]
Closing as this issue is addressed in PR https://github.com/wso2/carbon-apimgt/pull/10450

**Pull request closed without merging**
