### PR TITLE
Add client certificate api implementation.

### PR DESCRIPTION
**Pull request by menakaj**

### CODE REVIEW

**Comment by malinthaprasan** [comment]
@menakaj Do we add client certificates per API or global?
Just wondering this API should be as a base resource or as part of /apis/{apiId}/..

**Comment by menakaj** [comment]
@malinthaprasan Client certificate is added per api and subscription tier and access is being done with the certificate alias. It is also possible to use the api/{api_id} as the base resource.

Then it should be like: /api/{api_id}/certificates/{alias}

**Comment by malinthaprasan** [comment]
Since that is a cleaner approach. Shall we proceed with that?

**Comment by menakaj** [comment]
@malinthaprasan Will do.

**Pull request closed without merging**
