### PR TITLE
Refractor service catalog scope names and role names

### PR DESCRIPTION
**Pull request by ChamodDamitha**
Scopes

> service_catalog:view
> service_catalog:write
> service_catalog:entry_view
> service_catalog:entry_write

Roles

> Internal/service_catalog_admin
> Internal/service_catalog_user
> Internal/service_catalog_viewer

### CODE REVIEW

**Comment by fazlan-nazeem** [comment]
difference between service_catalog_browser and service_catalog_user is not that intuitive, I guess. Any better name suggestions?

**Comment by ChamodDamitha** [comment]
> difference between service_catalog_browser and service_catalog_user is not that intuitive, I guess. Any better name suggestions?

How about **service_catalog_writer** and **service_catalog_viewer/service_catalog_browser** ?

**Comment by fazlan-nazeem** [comment]
service_catalog_user and service_catalog_viewer seem to be better since the viewer suffix will indicate it's a read-only role.

**Comment by ChamodDamitha** [comment]
> service_catalog_user and service_catalog_viewer seem to be better since the viewer suffix will indicate it's a read-only role.

Updated

**Pull request merged**
