### PR TITLE
Fix Publisher and Store issues

### PR DESCRIPTION
**Pull request by tharikaGitHub**
This PR fixes the following issues.

https://github.com/wso2/product-apim/issues/5337
https://github.com/wso2/product-apim/issues/5346

### CODE REVIEW

**Comment by malinthaprasan** [comment]
@tharikaGitHub there seems to be a conflict after I merged the other PR https://github.com/wso2/carbon-apimgt/pull/6938

**Comment by tharikaGitHub** [comment]
@malinthaprasan Fixed.

**Comment by bhathiya** [comment]
@tharikaGitHub please fix the conflicts and merge.

**Comment by tharikaGitHub** [comment]
@bhathiya Fixed

**Comment by bhathiya** [comment]
> @bhathiya Fixed

can we merge now?

**Pull request merged**
